sudo: false
cache:
  directories:
    - ~/arduino_ide
    - ~/.arduino15/packages/
git:
  depth: false
  quiet: true
env:
  global:
     - ARDUINO_IDE_VERSION="1.8.7"
before_install:
  - source <(curl -SLs https://raw.githubusercontent.com/adafruit/travis-ci-arduino/master/install.sh)
install:
  # install lib
  # add your libs here, example:
  - rm -rf ~/arduino_ide/libraries/AsyncTCP
  - rm -rf ~/arduino_ide/libraries/ESPAsyncTCP
  - rm -rf ~/arduino_ide/libraries/ESPAsyncWebServer
  - rm -rf ~/arduino_ide/libraries/ESP-DASH
  - rm -rf ~/arduino_ide/libraries/ArduinoJson
  - git clone https://github.com/me-no-dev/AsyncTCP ~/arduino_ide/libraries/AsyncTCP
  - git clone https://github.com/me-no-dev/ESPAsyncTCP ~/arduino_ide/libraries/ESPAsyncTCP
  - git clone https://github.com/me-no-dev/ESPAsyncWebServer ~/arduino_ide/libraries/ESPAsyncWebServer
  - git clone https://github.com/bblanchon/ArduinoJson ~/arduino_ide/libraries/ArduinoJson
  - git clone https://github.com/ayushsharma82/ESP-DASH ~/arduino_ide/libraries/ESP-DASH
  - arduino --board esp32:esp32:featheresp32:FlashFreq=80 --save-prefs
script:
#compile the code, example:
 #- arduino -v --verbose-build --board esp8266:esp8266:huzzah:eesz=4M3M,xtal=80 ~/arduino_ide/libraries/ESP-DASH/examples/ESP8266_basic/ESP8266_basic.ino
 #- arduino --verify --board esp8266:esp8266:huzzah:eesz=4M3M,xtal=80 ~/arduino_ide/libraries/ESP-DASH/examples/ESP8266_blink/ESP8266_blink.ino
 #- arduino --verify --board esp8266:esp8266:huzzah:eesz=4M3M,xtal=80 ~/arduino_ide/libraries/ESP-DASH/examples/ESP8266_realtime/ESP8266_realtime.ino
 - arduino --verify --board esp32:esp32:featheresp32:FlashFreq=80 /usr/local/share/arduino/libraries/ESP-DASH/examples/ESP32_basic/ESP32_basic.ino
 - arduino --verify --board esp32:esp32:featheresp32:FlashFreq=80 /usr/local/share/arduino/libraries/ESP-DASH/examples/ESP32_blink/ESP32_blink.ino
 - arduino --verify --board esp32:esp32:featheresp32:FlashFreq=80 /usr/local/share/arduino/libraries/ESP-DASH/examples/ESP32_realtime/ESP32_realtime.ino
 
notifications:
  email:
    on_success: change
    on_failure: change
